### ISSUE TITLE
branch_OPEN on none attributed open events

### ISSUE THREAD

**Issue by DrBeak1** [BranchMetrics/Segment-Branch-iOS#12]
The branch_OPEN event is being sent to Segment even if I launch the app by tapping the icon on the device home screen. Not only that it is being set multiple times.

I can't imagine this is expected behavior.

<img width="665" alt="screen shot 2018-08-02 at 4 59 44 pm" src="https://user-images.githubusercontent.com/1033734/43617245-cc0a2e00-9675-11e8-9cca-e4170072aab9.png">

**Implementation**
```
    SEGAnalyticsConfiguration *configuration = [SEGAnalyticsConfiguration configurationWithWriteKey:kSegmentToken];
    //  ... other setup stuff
    [configuration use:[BNCBranchIntegrationFactory instance]];
    [SEGAnalytics setupWithConfiguration:configuration];

    [Branch setUseTestBranchKey:YES];
    [[Branch getInstance] setDebug];

    [[Branch getInstance] setRequestMetadataKey:@"$segment_anonymous_id"
                                          value:[[SEGAnalytics sharedAnalytics] getAnonymousId]];

    [[Branch getInstance] initSessionWithLaunchOptions:launchOptions
                            andRegisterDeepLinkHandler:^(NSDictionary * _Nonnull params, NSError * _Nullable error) {
                                // do stuff with deep link data (nav to page, display content, etc)
                                NSLog(@"deep link params: %@", params);
                            }];
```

**Questions:**
(1) Is this normal behavior?
(2) Did I implement the SDK incorrectly?

**Comment by Sarkar** [comment]
@DrBeak1 , we're investigating. This isn't normal behavior. There is a chance the implementation is incorrect, but @E-B-Smith from our team is investigating.

**Comment by DrBeak1** [comment]
Thanks @Sarkar & @E-B-Smith -- I plan to keep digging into this today and will update here if I sort things out. Note that I added a piece of my implementation to the above snippet that I forgot to include previously; related to debug/test modes.

**Comment by DrBeak1** [comment]
Another thing I'm seeing today:

1. This wasn't happening yesterday, which is odd because no code has changed, but all of my Segment events are being duplicated by Branch. So for example if I have "Viewed Menu", I also get "branch_Viewed Menu" - despite launching the app from the device home screen.

2. After registering the deep link handler, going into an email with a registered link, tapping the link to launch the app, the handler is never called.

**Comment by E-B-Smith** [comment]
Do you have web hooks or some other server-to-server integration enabled?

**Comment by DrBeak1** [comment]
No. The only thing set up for Branch.io is "Quick Links", and I enabled "Data Integrations" and set up Segment there.

So on the web side:
- Segment has Branch set up as a destination.
- Branch has Segment set up within Data Integrations.

I've also deleted the app from my device, reinstalled from xcode, and even after the delete/install branch is passing `branch_INSTALL` and `branch_OPEN` - as if the attribution was still intact after the app was deleted.

On [this page](https://docs.branch.io/pages/deep-linking/routing/) it mentions that if you "minimize and reopen the app, the session will be cleared and so will the data" - but it seems like the url property: `-d properties[+url]=https://myapp.test-app.link/no9Jgvkq2O \` never clears. In fact it seems to persist even through delete/reinstall. 

**EDIT:** ^ my last comment here may be related to the "Attribution Window" as defined in branch. That is: "Maximum time between a click or a web to app auto redirect and a user being deep linked." which is, by default, set to 120 minutes. So the persistence makes sense based on this. In fact, that explains why I'm seeing `branch_OPEN` even when I launch from the device home screen. 

Now the only question is why I'm seeing `branch_OPEN` happen 3x per app launch.

**Comment by DrBeak1** [comment]
Is it possible that the link clicks are compounding? What I mean by that, is if I click a deep link 3x within the Attribution Window, then launch the app - the app launch is then associated with all 3 links and therefore we see `branch_OPEN` 3x on a given app launch event.

I tried to test this theory by reducing the attribution window from 2 hours to 1 minute. I then deleted the app and reinstalled. In this case I saw 2 `branch_INSTALL` events. So either this theory is wrong and there is an issue elsewhere, OR adjusting the attribution window doesn't remove windows that are already in place. So I'm going to wait a couple of hours and try testing this again.

**Comment by E-B-Smith** [comment]
Thanks for really digging in to this.  I am hung up doing an errand but I'll get back to this when I can today.

You can look at the example that I tested with here:
https://github.com/BranchMetrics/Segment-Branch-iOS/tree/master/Examples/Fortune

I've seen issues similar to this before, but it's usually because people initialize Branch before Segment, or initialize twice  or something.  Looking at your code snippet, that doesn't seem to be the case.

**Comment by DrBeak1** [comment]
Shoot - I was really hopeful about that theory. 

- Waited 2 hours.
- Launched app.
- Still seeing branch_< event > in Segment debugger.
- Deleted the app.
- Hard reset on device.
- Reinstall
- Still seeing branch_< event > in Segment debugger.

Something has to be wrong with the SDK. I've spent a full day investigating this and comparing my set up to documentation and to example projects. The last thing I can do is dig into the SDK itself. That'll have to wait until next week.

**Comment by E-B-Smith** [comment]
I'm seeing a timing issue with opens in the SDK.  I'm working on it this morning and hopefully have something for you this afternoon.

**Comment by E-B-Smith** [comment]
@DrBeak1 

I updated the Segment-Branch integration to prevent double opens. Let me know if this fix works for you. You can pull the latest pod to get the update.

Sorry for your frustration and thanks for reporting the issue!

**Comment by DrBeak1** [comment]
@E-B-Smith 

Thanks for your help with this. I didn't touch my test device all weekend. I thought that would give ample time for any association between link-click and app events to dissolve. This morning I deleted the latest build of our app from the device, hard reset, then fresh install. 

Still seeing some issues:
![image](https://user-images.githubusercontent.com/1033734/43739809-2436a3c8-997e-11e8-9014-582211317214.png)

It looks as though it is still associating the installation via Xcode with link-clicks that occurred on Friday last week. On top of that, it is passing the `branch_INSTALL` event twice.

Other points:

- I tested launching from the link and it initially worked. 1 `branch_OPEN` and `Application Opened` event. 
- However, killing the app in Xcode then starting it again kicked off the same issue we were seeing last week. 3 `branch_OPEN` for every 1 `Application Opened` event.

Can you tell me if the `branch_< event>` events are being triggered on the client or if they're being fired off by Branch.io server-side?

**Comment by E-B-Smith** [comment]
First, pull the latest Segment-Branch integration to prevent the double attribution.

Second, to reset the device associations, you'll need to remove your test app from your device, then on the phone go to Settings > Privacy > Advertising > Reset Advertising Identifier

If 'Limit Ad Tracking' is on, turn it off.  

Now build and run your app on your device.

Branch analytics should make a new attribution for your phone.

**Comment by DrBeak1** [comment]
@E-B-Smith - After updating the pod and following your steps above, I was still having this issue. 3x1 `branch_OPEN` to `Application Open`. 

I dug into the Branch SDK and found that `Branch.m`'s `initUserSessionAndCallCallback:` function was being called multiple times. And because `self.isInitialized` is not set to true until the process completes, the session was being restarted exactly the same number of times as I was seeing `branch_OPEN`'s. To fix this I changed the `self.isInitialized` boolean to a `BNCInitStatus` enum, where when the process of initialization begins I update the status to `Initializing` -- and change the `if` conditional to only call `initializeSession` if the current status is `None` (not a good name), indicating that the process has either not started, or failed. Further, where `self.isInitialized` was being set to true, I'm setting the new enum property to `Initialized`. After doing this I'm seeing the correct number of events, 1x1, on each open and installation of the app. Seems like a simple race condition.

Thoughts?

**Comment by DrBeak1** [comment]
Further inspection shows that `BNCBranchIntegration.m` is calling `[[Branch getInstance] initSessionWithLaunchOptions:` inside it's `applicationDidFinishLaunching:` function and I'm also calling `[[Branch getInstance] initSessionWithLaunchOptions:launchOptions:andRegisterDeepLinkHandler:` (as shown in my implementation above) -- it's because both of these call the init function that I was seeing multiple `branch_< event>` events. 

Is there any reason for `BNCBranchIntegration.m` to call `applicationDidFinishLaunching:(NSNotification *)notification` if it already has to be called manually to register the deep link handler?

**Comment by DrBeak1** [comment]
@E-B-Smith I created a [PR](https://github.com/BranchMetrics/ios-branch-deep-linking/pull/849) for the changes I made. Whether it gets approved or not I figured it'd be the easiest way to illustrate the changes I made to you.

**Comment by E-B-Smith** [comment]
Thanks -- I merged the PR and I'm testing it now.  I need to fix a couple small things and QA before I can release to master.

**Comment by DrBeak1** [comment]
@E-B-Smith - I see the changes I made were released today. Thanks for helping with this. Going to close this issue now.
