### ISSUE TITLE
Add documentation for branch callback

### ISSUE THREAD

**Issue by IsaiahJTurner** [BranchMetrics/Segment-Branch-iOS#16]
The documentation for `Segment-Branch` leaves me confused when it redirects back to the standard documentation. Do I still need the standard Branch library when using this? How do I handle links?

**Comment by E-B-Smith** [comment]
The standard Branch is installed when using the Segment-Branch-iOS kit when you install with CocoaPods.

I am in the middle of updating the documentation to be clearer, but the gist is:

1. Install with CocoaPods as shown in the current ReadMe in the project.
2. Add the code stubs as shown, like
              [[SEGAnalytics shared] continueUserActivity:userActivity];
    etc.
3. Add a deep link handler callback block, like:

```Swift
   // Swift
    let configuration = SEGAnalyticsConfiguration(writeKey: "6ViWbAkMJGarxYDMiDkrn2BQoeYqrbIm")
    configuration.use(BNCBranchIntegrationFactory.instance())
    configuration.trackApplicationLifecycleEvents = true
    SEGAnalytics.setup(with: configuration)
    Branch.getInstance().sessionInitWithParamsCallback = {
        (params: [AnyHashable: Any]?, error: Error?) -> Void in
            if let error = error {
                // An error occurred
            }
            else
            if let deepLinked:Bool = params?["+clicked_branch_link"] as? Bool, deepLinked {
                // A deep link happened!  Handle it...
            }
    }
```

**Comment by IsaiahJTurner** [comment]
Exactly what I needed, thank you!
