### ISSUE TITLE
Update dependencies to support Segment 3.2.4

### ISSUE THREAD

**Issue by emkman** [BranchMetrics/Segment-Branch-iOS#3]
Podspec currently locks the main Analytics SDK to ~> 3.0.0 and is two minor versions behind.

**Comment by aaustin** [comment]
Fixed ! https://github.com/BranchMetrics/Segment-Branch-iOS/commit/6a30a40dc78f2e2025dd89f5fbf7b69d495ca84f Pod deploy coming soon.
