### ISSUE TITLE
Branch Track Commerce using Segment

### ISSUE THREAD

**Issue by liemlyquan** [BranchMetrics/Segment-Branch-iOS#7]
Currently, Segment has had `Order Completed` event, which is transferable to other services. However, it is not yet compatible with Branch `Track Commerce`.  So in this case, we are using two different functions to track the purchase of user. 

`https://docs.branch.io/pages/apps/ios/#track-commerce`
`https://segment.com/docs/spec/ecommerce/v2/#core-ordering`

cc @constantx

**Comment by E-B-Smith** [comment]
Thanks for pointing this out: That is a pain.  

I can definitely simplify this in the Segment / Branch integration.

**Comment by E-B-Smith** [comment]
Also, have you thought of using the Branch - Segment data integration?

This is a Branch server to Segment server integration.  This may save you a ton of time and effort:

https://branch.dashboard.branch.io/data-import-export/data-feeds/landing?from=%2Fdata-import-export%2Fdata-feeds%2Fintegrations

**Comment by liemlyquan** [comment]
The link points me to a website requires login. I think what it supposed to redirect me to is Data Import & Export -> Data -> Integrations ?

However, what we are aiming at is Segment->Branch, not Branch->Segment. since we have already written tracking for Segment

**Comment by E-B-Smith** [comment]
In that case we at Branch should probably update the Branch-Segment integration to incorporate our new event tracking, which will include the commerce events.

There are no shortcuts, apparently.
@derrickstaten

**Comment by E-B-Smith** [comment]
I've finally been able to get around to adding the events to the Segment-Branch integration. 

If you pull the latest version of this project you'll get the latest changes.

Here's the PR:
https://github.com/BranchMetrics/Segment-Branch-iOS/pull/9
